# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True)),
                ('address', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
