# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160415_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='basket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Basket'),
        ),
    ]
