# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160419_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
