# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-16 08:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20160415_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='shoppingItem',
        ),
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='state',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
