# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_client'),
        ('main', '0005_product_premium'),
    ]

    operations = [
    ]
