# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160417_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
