# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160417_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='session',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
