# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-17 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160417_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='create_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='session',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
