# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20160417_2339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ('id',), 'verbose_name': 'ShoppingItem', 'verbose_name_plural': 'ShoppingItems'},
        ),
    ]
